### ISSUE TITLE
crash on reload of configuration run remotely

### ISSUE THREAD

**Issue by alja** [alja/cmssw#69]
gcc491/cms/cmssw/CMSSW_7_5_4/external/slc6_amd64_gcc491/data/Fireworks/Geometry/data/cmsGeom10.root
Info: Search files at http://uaf-2.t2.ucsd.edu/fireworks/7/.
Info: Checking process history. http://uaf-2.t2.ucsd.edu/fireworks/7/DoubleMu-miniaod.root latest process "reHLT", version "CMSSW_7_4_1"
Info: Set current file to http://uaf-2.t2.ucsd.edu/fireworks/7/DoubleMu-miniaod.root.
Info: Loading configuration file miniaod.fwc
libpng warning: Interlace handling should be turned on when using png_read_image
Error in <RootX11ErrorHandler>: GLXBadContextTag (TGLWidget XID: 6293180, XREQ: 150)
TGLWidget:	6293180
	TGCompositeFrame:	6293172
	TGCompositeFrame:	6293171
	TEveCompositeFrameInPack:	6293126
	TGPack:	6292563
	TEveCompositeFrameInPack:	6292513
	TGPack:	6292502
	CmsShowMainFrame:	6292290

^C
Program received signal SIGINT, Interrupt.
0x0000003fe0a0e2e4 in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x0000003fe0a0e2e4 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003fe0a09588 in _L_lock_854 () from /lib64/libpthread.so.0
#2  0x0000003fe0a09457 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000003fe361adff in glXDestroyContext () from /usr/lib64/libGL.so.1
#4  0x00007ffff340ae59 in TGLContext::Release() ()
   from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_4/external/slc6_amd64_gcc491/lib/libRGL.so
#5  0x00007ffff349f399 in TGLWidget::~TGLWidget() ()
   from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_4/external/slc6_amd64_gcc491/lib/libRGL.so
#6  0x00007ffff349f439 in TGLWidget::~TGLWidget() ()
   from /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_4/external/slc6_amd64_gcc491/lib/libRGL.so
#7  0x00007fffefc4bf04 in ?? ()

**Comment by alja** [comment]
a soultion would be not to ceate any window before startup ....
